name: Update Operations Issue Fields
on:
  issues:
    types: [opened]

jobs:
  update-fields:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'triage')
    steps:
      - name: Extract Fields from Issue Body
        id: extract_fields
        run: |
          DUE_DATE=$(awk -v RS="" '/### Due Date/ {print $3}' <<< "${{ github.event.issue.body }}")
          PRIORITY=$(awk -v RS="" '/### Priority/ {print $3,$4,$5,$6,$7}' <<< "${{ github.event.issue.body }}")
          EFFORT=$(awk -v RS="" '/### Level of Effort/ {print $4,$5,$6}' <<< "${{ github.event.issue.body }}")

          echo "DUE_DATE=$DUE_DATE" >> $GITHUB_ENV
          echo "PRIORITY=$PRIORITY" >> $GITHUB_ENV
          echo "EFFORT=$EFFORT" >> $GITHUB_ENV

      - name: Update Project Fields
        run: |
          gh project item-edit --project-id "$PROJECT_ID" --id "$ISSUE_ID" \
            --field-id "PVTF_lADOBfaOE84ATF4czgpFJGw" --text "$DUE_DATE" \
            --field-id "PVTSSF_lADOBfaOE84ATF4czgpFJPM" --text "$PRIORITY" \
            --field-id "PVTSSF_lADOBfaOE84ATF4czgpFJSo" --text "$EFFORT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_ID: "PVT_kwDOBfaOE84ATF4c"  # Your GitHub Project ID
          ISSUE_ID: ${{ github.event.issue.node_id }}
          DUE_DATE: ${{ env.DUE_DATE }}  # Ensure these are set earlier in your workflow
          PRIORITY: ${{ env.PRIORITY }}
          EFFORT: ${{ env.EFFORT }}
