name: Update Operations Issue Fields
on:
  issues:
    types: [opened]

jobs:
  update-fields:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'triage')
    steps:
      - name: Update Project Fields
        run: |
          gh project item-update $PROJECT_ID --owner $OWNER --item-id $ISSUE_ID \
            --field "Due Date=${{ fromJson(github.event.issue.body).due_date }}" \
            --field "Priority=${{ fromJson(github.event.issue.body).priority }}" \
            --field "Level of Effort=${{ fromJson(github.event.issue.body).level_of_effort }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_ID: "2"
          OWNER: "bruthurs-inc"
          ISSUE_ID: ${{ github.event.issue.node_id }}
          
