name: Map Issue Fields to Project
on:
  issues:
    types: [opened]

jobs:
  update-project-fields:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Issue Fields & Update Project
        env:
          GH_TOKEN: ${{ secrets.PROJECT_PAT }}
        run: |
          set -e  # Exit immediately if a command fails

          echo "Extracting issue fields..."
          ISSUE_BODY="${{ github.event.issue.body }}"
          echo "Issue Body: $ISSUE_BODY"

          # Extract values using awk
          PRIORITY=$(echo "$ISSUE_BODY" | awk -v RS='' '/### Priority/ {getline; print}')
          EFFORT=$(echo "$ISSUE_BODY" | awk -v RS='' '/### Level of Effort/ {getline; print}')
          DUE_DATE=$(echo "$ISSUE_BODY" | awk -v RS='' '/### Due Date/ {getline; print}')

          echo "Extracted Priority: '$PRIORITY'"
          echo "Extracted Effort: '$EFFORT'"
          echo "Extracted Due Date: '$DUE_DATE'"

          # Fetch project fields
          echo "Fetching project fields..."
          PROJECT_FIELDS=$(gh api graphql -F projectId="PVT_kwDOBfaOE84ATF4c" -f query='
            query($projectId: ID!) {
              node(id: $projectId) {
                ... on ProjectV2 {
                  fields(first: 100) {
                    nodes {
                      id
                      name
                      ... on ProjectV2SingleSelectField {
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }')

          echo "Received Project Fields JSON:"
          echo "$PROJECT_FIELDS" | jq .

          # Extract field options
          echo "Extracting field options..."
          PRIORITY_OPTION_ID=$(echo "$PROJECT_FIELDS" | jq -r --arg priority "$PRIORITY" '
            .data.node.fields.nodes[] | select(.name == "Priority") | .options[] |
            select(.name == $priority) | .id')

          EFFORT_OPTION_ID=$(echo "$PROJECT_FIELDS" | jq -r --arg effort "$EFFORT" '
            .data.node.fields.nodes[] | select(.name == "Effort") | .options[] |
            select(.name == $effort) | .id')

          echo "Priority Option ID: '$PRIORITY_OPTION_ID'"
          echo "Effort Option ID: '$EFFORT_OPTION_ID'"

          # Convert Due Date to ISO 8601 format
          echo "Converting due date..."
          if [[ -n "$DUE_DATE" ]]; then
            DUE_DATE_ISO=$(date -d "$DUE_DATE" --iso-8601=seconds || echo "")
          else
            DUE_DATE_ISO=""
          fi

          echo "Due Date (ISO): '$DUE_DATE_ISO'"

          # Fetch project item ID
          echo "Fetching project item ID..."
          ITEM_ID=$(gh api graphql -F projectId="PVT_kwDOBfaOE84ATF4c" -F contentId="${{ github.event.issue.node_id }}" -f query='
            query($projectId: ID!, $contentId: ID!) {
              node(id: $projectId) {
                ... on ProjectV2 {
                  items(first: 100) {
                    nodes {
                      id
                      content {
                        ... on Issue { id }
                      }
                    }
                  }
                }
              }
            }' --jq '.data.node.items.nodes[] | select(.content.id == "${{ github.event.issue.node_id }}") | .id')

          echo "Project Item ID: '$ITEM_ID'"

          # Check if required values are empty
          if [[ -z "$PRIORITY_OPTION_ID" || -z "$EFFORT_OPTION_ID" || -z "$DUE_DATE_ISO" || -z "$ITEM_ID" ]]; then
            echo "Error: One or more required values are empty."
            exit 1
          fi

          # Update project fields
          echo "Updating project fields..."
          gh api graphql -F itemId="$ITEM_ID" -F projectId="PVT_kwDOBfaOE84ATF4c" -f query='
            mutation ($itemId: ID!, $projectId: ID!) {
              updatePriority: updateProjectV2ItemFieldValue(
                input: {
                  projectId: $projectId,
                  itemId: $itemId,
                  fieldId: "PVTSSF_lADOBfaOE84ATF4czgpFJPM",
                  value: { singleSelectOptionId: "'"$PRIORITY_OPTION_ID"'" }
                }
              ) { clientMutationId }

              updateEffort: updateProjectV2ItemFieldValue(
                input: {
                  projectId: $projectId,
                  itemId: $itemId,
                  fieldId: "PVTSSF_lADOBfaOE84ATF4czgpFJSo",
                  value: { singleSelectOptionId: "'"$EFFORT_OPTION_ID"'" }
                }
              ) { clientMutationId }

              updateDueDate: updateProjectV2ItemFieldValue(
                input: {
                  projectId: $projectId,
                  itemId: $itemId,
                  fieldId: "PVTF_lADOBfaOE84ATF4czgpFJGw",
                  value: { date: "'"$DUE_DATE_ISO"'" }
                }
              ) { clientMutationId }
            }'
