name: Map Operations Issue Fields to Project

on:
  issues:
    types:
      - opened

jobs:
  map-fields:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "triage" label
        if: contains(github.event.issue.labels.*.name, 'triage')
        run: echo "Issue contains the 'triage' label. Proceeding with field mapping."

      - name: Extract Issue Fields
        id: extract_fields
        run: |
          PRIORITY=$(echo "${{ github.event.issue.body }}" | grep -A1 "### Priority" | tail -n1 | xargs)
          EFFORT=$(echo "${{ github.event.issue.body }}" | grep -A1 "### Level of Effort" | tail -n1 | xargs)
          DUE_DATE=$(echo "${{ github.event.issue.body }}" | grep -A1 "### Due Date" | tail -n1 | xargs)

          echo "priority=$PRIORITY" >> $GITHUB_ENV
          echo "effort=$EFFORT" >> $GITHUB_ENV
          echo "due_date=$DUE_DATE" >> $GITHUB_ENV

      - name: Add Issue to Project and Set Fields
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/bruthurs-inc/projects/2
          github-token: ${{ secrets.PROJECT_PAT }}
          content-id: ${{ github.event.issue.node_id }}
          fields: |
            Priority: ${{ env.priority }}
            Level of Effort: ${{ env.effort }}
            Due Date: ${{ env.due_date }}
